version: 2.1

jobs:
  Build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
      - run: 
          name: Install Gradlew and Build
          command: sh ./gradlew build -x test
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
          paths:
            - ./.gradle
      - persist_to_workspace:
          root: .
          paths:
            - .  

  Unit Test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Unit Test
          command: |
            sh ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .  
      - store_test_results:
          path: build/test-results/test/
      - store_artifacts: 
          path: build/reports/tests/test/

  Static Code Analysis:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: ls build/
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube
  
  Build and Upload Docker:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t victormcl/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM .
      - run:
          name: Login Docker HUB
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push Docker image
          command: docker push victormcl/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - Build:
          context: sonarcloud
      - Unit Test:
          context: sonarcloud
          requires:
            - Build
      - Static Code Analysis:
          context: sonarcloud
          requires:
            - Unit Test
      #- Build and Upload Docker:
      #    context: sonarcloud
      #    requires:
      #      - Static Code Analysis
      #    filters:
      #      branches:
      #        only: master